### ISSUE TITLE
should be org website

### ISSUE THREAD

**Issue by ligi** [goerli/.net#3]
currently this points to goerli.com - I think pointing to this site (goerli.net) would be much nicer

![image](https://user-images.githubusercontent.com/111600/51445606-8a132d80-1d07-11e9-94fc-bb49ab48a333.png)

**Comment by chrisfenos** [comment]
@ligi  I agree that the goerlicon website looks cool and we should keep that as the main web reference until the .com is redesigned. Some of this will be complete at goerlicon so we can always move it back to .com if we feel the need.

**Comment by 5chdn** [comment]
Done
