### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by chrisfenos** [goerli/.net#4]
love the site, only issue i would raise is that there is no favicon for the webpage. Just a missing file icon in the browser tab. I assumed the github repo image was our logo, maybe you want to design a new one or I could get one for us? Either way we should get a high resolution standardized image that could be used across applications for a consistent goerli branding.

**Comment by 5chdn** [comment]
@Lililashka when favicon :relaxed:

**Comment by 5chdn** [comment]
done
